version: '3.8'

services:
    app:
        image: php:latest
        restart: always
        ports: 
            - 8000:8000
        volumes:
            - ./:/app
        working_dir: /app
        command: ['php', 'artisan', 'serve', '--host=0.0.0.0', '--port=8000']
    node:
        image: node:latest
        restart: always
        volumes:
            - ./:/app
        working_dir: /app
        command: ['npm', 'run', 'watch']
